In [1]:
# Cell 1: Import Libraries
import fastf1
import pandas as pd
import os

print("All libraries imported successfully!")
print(f"FastF1 version: {fastf1.__version__}")

All libraries imported successfully!
FastF1 version: 3.8.3

In [2]:
# Cell 2: Set up cache
cache_path = "../data/raw/cache"
os.makedirs(cache_path, exist_ok=True)

fastf1.Cache.enable_cache(cache_path)
print(f"Cache enabled at: {cache_path}")

Cache enabled at: ../data/raw/cache

In [3]:
# Cell 3: Load 2023 Australian Grand Prix race session
session = fastf1.get_session(2023, 'Australia', 'R')
session.load()

print("Session loaded!")
print(f"Event: {session.event['EventName']}")
print(f"Date: {session.event['EventDate']}")
print(f"Circuit: {session.event['Location']}")

core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver 241: Position data is incomplete!
_api        WARNING 	Driver 242: Position data is incomplete!
_api        WARNING 	Driver 243: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '44', '14', '18', '11', '4', '27', '81', '24', '22', '77', '55', '10', '31', '21', '2', '20', '63', '23', '16']

Session loaded!
Event: Australian Grand Prix
Date: 2023-04-02 00:00:00
Circuit: Melbourne

In [4]:
# Cell 4: Explore race results
results = session.results

results_clean = results[[
    'DriverNumber', 'Abbreviation', 'FullName',
    'TeamName', 'GridPosition', 'Position',
    'Points', 'Status'
]]

print(f"Number of drivers: {len(results_clean)}")
print("\nRace Results:")
results_clean

Number of drivers: 20

Race Results:

,DriverNumber,Abbreviation,FullName,TeamName,GridPosition,Position,Points,Status
1,1,VER,Max Verstappen,Red Bull Racing,1.0,1.0,25.0,Finished
44,44,HAM,Lewis Hamilton,Mercedes,3.0,2.0,18.0,Finished
14,14,ALO,Fernando Alonso,Aston Martin,4.0,3.0,15.0,Finished
18,18,STR,Lance Stroll,Aston Martin,6.0,4.0,12.0,Finished
11,11,PER,Sergio Perez,Red Bull Racing,20.0,5.0,11.0,Finished
4,4,NOR,Lando Norris,McLaren,13.0,6.0,8.0,Finished
27,27,HUL,Nico Hulkenberg,Haas F1 Team,10.0,7.0,6.0,Finished
81,81,PIA,Oscar Piastri,McLaren,16.0,8.0,4.0,Finished
24,24,ZHO,Guanyu Zhou,Alfa Romeo,17.0,9.0,2.0,Finished
22,22,TSU,Yuki Tsunoda,AlphaTauri,12.0,10.0,1.0,Finished
77,77,BOT,Valtteri Bottas,Alfa Romeo,19.0,11.0,0.0,Finished
55,55,SAI,Carlos Sainz,Ferrari,5.0,12.0,0.0,Finished
10,10,GAS,Pierre Gasly,Alpine,9.0,13.0,0.0,Retired
31,31,OCO,Esteban Ocon,Alpine,11.0,14.0,0.0,Retired
21,21,DEV,Nyck De Vries,AlphaTauri,15.0,15.0,0.0,Retired
2,2,SAR,Logan Sargeant,Williams,18.0,16.0,0.0,Retired
20,20,MAG,Kevin Magnussen,Haas F1 Team,14.0,17.0,0.0,Retired
63,63,RUS,George Russell,Mercedes,2.0,18.0,0.0,Retired
23,23,ALB,Alexander Albon,Williams,8.0,19.0,0.0,Retired
16,16,LEC,Charles Leclerc,Ferrari,7.0,20.0,0.0,Retired

In [5]:
# Cell 5: Save to CSV
output_path = "../data/raw/2023_australia_race_results.csv"
results_clean.to_csv(output_path, index=False)
print(f"Data saved to: {output_path}")
print(f"Shape: {results_clean.shape[0]} rows, {results_clean.shape[1]} columns")

Data saved to: ../data/raw/2023_australia_race_results.csv
Shape: 20 rows, 8 columns

In [6]:
# Cell 6: Collect multiple races across seasons
# We'll collect a full season worth of races

races_to_collect = [
    (2023, 'Bahrain'),
    (2023, 'Saudi Arabia'),
    (2023, 'Australia'),
    (2023, 'Azerbaijan'),
    (2023, 'Miami'),
    (2023, 'Monaco'),
    (2023, 'Spain'),
    (2023, 'Canada'),
    (2023, 'Britain'),
    (2023, 'Hungary'),
]

all_results = []

for year, race in races_to_collect:
    try:
        print(f"Loading {year} {race}...")
        s = fastf1.get_session(year, race, 'R')
        s.load(telemetry=False, weather=False, messages=False)
        
        r = s.results[['DriverNumber', 'Abbreviation', 'FullName',
                        'TeamName', 'GridPosition', 'Position',
                        'Points', 'Status']].copy()
        r['Year'] = year
        r['Race'] = race
        all_results.append(r)
        print(f"  ✓ {len(r)} drivers loaded")
        
    except Exception as e:
        print(f"  ✗ Failed: {e}")

# Combine all races into one dataframe
df = pd.concat(all_results, ignore_index=True)
print(f"\nTotal records collected: {len(df)}")
df.head(10)

Loading 2023 Bahrain...

Request for URL https://raw.githubusercontent.com/theOehrly/f1schedule/master/schedule_2023.json failed; using cached response
Traceback (most recent call last):
  File "d:\datascience\F1-race-predictor\venv\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "d:\datascience\F1-race-predictor\venv\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "d:\datascience\F1-race-predictor\venv\Lib\site-packages\urllib3\connection.py", line 571, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wilder\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\wilder\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wilder\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\datascience\F1-race-predictor\venv\Lib\site-packages\requests\adapters.py", line 645, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "d:\datascience\F1-race-predictor\venv\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "d:\datascience\F1-race-predictor\venv\Lib\site-packages\urllib3\util\retry.py", line 490, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\datascience\F1-race-predictor\venv\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "d:\datascience\F1-race-predictor\venv\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "d:\datascience\F1-race-predictor\venv\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "d:\datascience\F1-race-predictor\venv\Lib\site-packages\urllib3\connection.py", line 571, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wilder\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\wilder\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wilder\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\datascience\F1-race-predictor\venv\Lib\site-packages\requests_cache\session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\datascience\F1-race-predictor\venv\Lib\site-packages\requests_cache\session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\datascience\F1-race-predictor\venv\Lib\site-packages\fastf1\req.py", line 112, in send
    return super().send(request, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\datascience\F1-race-predictor\venv\Lib\site-packages\requests\sessions.py", line 706, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\datascience\F1-race-predictor\venv\Lib\site-packages\requests\adapters.py", line 660, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '14', '55', '44', '18', '63', '77', '10', '23', '22', '2', '20', '21', '27', '24', '4', '31', '16', '81']

  ✓ 20 drivers loaded
Loading 2023 Saudi Arabia...

core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	Driver 11 completed the race distance 00:00.035000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['11', '1', '14', '63', '44', '55', '16', '31', '10', '20', '22', '27', '24', '21', '81', '2', '4', '77', '23', '18']
core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data

  ✓ 20 drivers loaded
Loading 2023 Australia...

req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '44', '14', '18', '11', '4', '27', '81', '24', '22', '77', '55', '10', '31', '21', '2', '20', '63', '23', '16']
core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

  ✓ 20 drivers loaded
Loading 2023 Azerbaijan...

req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['11', '1', '16', '14', '55', '44', '18', '63', '4', '22', '81', '23', '20', '10', '31', '2', '27', '77', '24', '21']
core           INFO 	Loading data for Miami Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

  ✓ 20 drivers loaded
Loading 2023 Miami...

req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '14', '63', '55', '44', '16', '10', '31', '20', '22', '18', '77', '23', '27', '24', '4', '21', '81', '2']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

  ✓ 20 drivers loaded
Loading 2023 Monaco...

req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '14', '31', '44', '63', '16', '10', '55', '4', '81', '77', '21', '24', '23', '22', '11', '27', '2', '20', '18']
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

  ✓ 20 drivers loaded
Loading 2023 Spain...

req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	Driver 1 completed the race distance 00:00.037000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['1', '44', '63', '11', '55', '18', '14', '31', '24', '10', '16', '22', '81', '21', '27', '23', '4', '20', '77', '2']
core           INFO 	Loading data for Canadian Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

  ✓ 20 drivers loaded
Loading 2023 Canada...

req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '22'
core           INFO 	Finished loading data for 20 drivers: ['1', '14', '44', '16', '55', '11', '23', '31', '18', '77', '81', '10', '4', '22', '27', '24', '20', '21', '63', '2']
core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

  ✓ 20 drivers loaded
Loading 2023 Britain...

req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '44', '81', '63', '11', '14', '23', '16', '55', '2', '77', '27', '18', '24', '22', '21', '10', '20', '31']
core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

  ✓ 20 drivers loaded
Loading 2023 Hungary...

req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
_api        WARNING 	Failed to align laps for drivers: ['10', '31']
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '11', '44', '81', '63', '16', '55', '14', '18', '23', '77', '3', '27', '22', '24', '20', '2', '31', '10']

  ✓ 20 drivers loaded

Total records collected: 200

,DriverNumber,Abbreviation,FullName,TeamName,GridPosition,Position,Points,Status,Year,Race
0,1,VER,Max Verstappen,Red Bull Racing,1.0,1.0,25.0,Finished,2023,Bahrain
1,11,PER,Sergio Perez,Red Bull Racing,2.0,2.0,18.0,Finished,2023,Bahrain
2,14,ALO,Fernando Alonso,Aston Martin,5.0,3.0,15.0,Finished,2023,Bahrain
3,55,SAI,Carlos Sainz,Ferrari,4.0,4.0,12.0,Finished,2023,Bahrain
4,44,HAM,Lewis Hamilton,Mercedes,7.0,5.0,10.0,Finished,2023,Bahrain
5,18,STR,Lance Stroll,Aston Martin,8.0,6.0,8.0,Finished,2023,Bahrain
6,63,RUS,George Russell,Mercedes,6.0,7.0,6.0,Finished,2023,Bahrain
7,77,BOT,Valtteri Bottas,Alfa Romeo,12.0,8.0,4.0,Finished,2023,Bahrain
8,10,GAS,Pierre Gasly,Alpine,20.0,9.0,2.0,Finished,2023,Bahrain
9,23,ALB,Alexander Albon,Williams,15.0,10.0,1.0,Finished,2023,Bahrain

In [7]:
# Cell 7: Save combined dataset
output_path = "../data/raw/2023_races_combined.csv"
df.to_csv(output_path, index=False)

print(f"Dataset saved!")
print(f"Total rows: {df.shape[0]}")
print(f"Total columns: {df.shape[1]}")
print(f"\nRaces collected: {df['Race'].unique()}")
print(f"\nColumn names: {list(df.columns)}")

Dataset saved!
Total rows: 200
Total columns: 10

Races collected: ['Bahrain' 'Saudi Arabia' 'Australia' 'Azerbaijan' 'Miami' 'Monaco'
 'Spain' 'Canada' 'Britain' 'Hungary']

Column names: ['DriverNumber', 'Abbreviation', 'FullName', 'TeamName', 'GridPosition', 'Position', 'Points', 'Status', 'Year', 'Race']

In [8]:
# Cell 8: Understand our data better
print("=== DATA OVERVIEW ===")
print(f"\nShape: {df.shape}")
print(f"\nData types:\n{df.dtypes}")
print(f"\nMissing values:\n{df.isnull().sum()}")
print(f"\nSample rows:")
df.sample(5)

=== DATA OVERVIEW ===

Shape: (200, 10)

Data types:
DriverNumber     object
Abbreviation     object
FullName         object
TeamName         object
GridPosition    float64
Position        float64
Points          float64
Status           object
Year              int64
Race             object
dtype: object

Missing values:
DriverNumber    0
Abbreviation    0
FullName        0
TeamName        0
GridPosition    0
Position        0
Points          0
Status          0
Year            0
Race            0
dtype: int64

Sample rows:

,DriverNumber,Abbreviation,FullName,TeamName,GridPosition,Position,Points,Status,Year,Race
4,44,HAM,Lewis Hamilton,Mercedes,7.0,5.0,10.0,Finished,2023,Bahrain
117,2,SAR,Logan Sargeant,Williams,16.0,18.0,0.0,Lapped,2023,Monaco
128,24,ZHO,Guanyu Zhou,Alfa Romeo,13.0,9.0,2.0,Finished,2023,Spain
175,22,TSU,Yuki Tsunoda,AlphaTauri,16.0,16.0,0.0,Finished,2023,Britain
21,1,VER,Max Verstappen,Red Bull Racing,15.0,2.0,19.0,Finished,2023,Saudi Arabia